version: '3.7'
services:
  web:
    image: library/abouerp:latest
    networks:
      - library
    depends_on:
      - mysql
      - redis
      - rabbitmq
    ports:
      - 80:8080
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./deploy/resources/application.yml:/app/resources/application.yml:ro
    restart: always

  mysql:
    image: mysql
    networks:
      - library
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./deploy/mysql/mysql.cnf:/etc/mysql/conf.d/mysql.cnf:ro
      - library_mysql_data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    restart: always

  redis:
    image: redis
    networks:
      - library
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - library_redis_data:/data
    restart: always

  rabbitmq:
    hostname: rabbitmq
    image: rabbitmq:management
    networks:
      - library
    ports:
      - 15672:15672
      - 5672:5672
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - library_rabbitmq_data:/data
    environment:
      RABBITMQ_DEFAULT_VHOST: "my_rabbitmq"
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "admin"
    restart: always

etworks:
  library:
    external: true

volumes:
  library_mysql_data:
    external: true
  library_redis_data:
    external: true
  library_rabbitmq_data:
    external: true


