server:
  port: 9090
spring:
  application:
    name: library
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/library?createDatabaseIfNotExist=true&serverTimezone=UTC&characterEncoding=utf8
    username: root
    password: root

  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        globally_quoted_identifiers: true
        globally_quoted_identifiers_skip_column_definitions: true
        dialect: org.hibernate.dialect.MySQL57InnoDBDialect
    open-in-view: true
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
  data:
    redis:
      repositories:
        enabled: false
  rabbitmq:
    username: admin
    password: admin
    port: 5672
    host: localhost
    virtual-host: /

logging:
  level:
    com.abouerp: debug
storage:
  location: f://upload/Downloads/library/
elasticsearch:
  url: 127.0.0.1:9200
